[package]
name = "kernel-r"
version = "0.1.0"
edition = "2024"

[dependencies]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# Fix for rust analyzer showing error on panic handler
# Also double [[]] since bin can show up mutliple times
[[bin]]
name = "blog_os"
test = false
bench = false
